### PR TITLE
added option to change colors on underlines on the top bar

### PR DESCRIPTION
**Pull request by brorbw**
This option is a bit hacked as i didn't have the time to fully understand how `bar_prepare_line` works. If you have some ideas about how to refactor to avoid code duplication I would be more than happy to discuss. Also this is my first C PR so be kind. There is also an issue with the length of the commands and naming that kinda violates the current indentation. Im not sure if that is a convention of C99 or something that @koekeishiya did.  

The following commands will be availabe after this PR
yabai -m config status_bar_space_underline_color 0xAARRGGBB
yabai -m config status_bar_power_underline_color 0xAARRGGBB
yabai -m config status_bar_clock_underline_color 0xAARRGGBB

### CODE REVIEW

**Comment by koekeishiya** [comment]
I'm not really interested in having changes to the bar upstream. It is meant to be pretty dumb and simple, which is why the code is written as it is. I don't think adding tons of commands such as these is the proper way to design a bar that people can customize. It should be done from scratch in a modular way.

**Comment by brorbw** [comment]
I completely agree with your statement. However compared to Ubersicht I like your bar better because it is has a smaller footprint. And even though it is thought of as a dumb bar I see no reason to hardcode the colors of the underlines when you can change the colors of the font as well as the color of the bg and fg.

A bar for macOS is an interesting discussion and while I know that it has been solved more than once on macOS the current solutions lack in either performance or features. 

I have removed the three additional commits in this PR because they do not relate to this feature.

**Comment by friederbluemle** [comment]
> There is also an issue with the length of the commands and naming that kinda violates the current indentation.

That's because the added lines use tabs for indentation:

image

If you set your editor to use 4 space like the rest of this codebase it'll all line up nicely.

A Chrome extension that allows you to see whitespace on GitHub is called [Render Whitespace on GitHub](https://chrome.google.com/webstore/detail/render-whitespace-on-gith/ifdbipohclgnokjgpejhnbjdlgjkkhom)

**Comment by brorbw** [comment]
I'm not sure what you are citing but I can set that up. It's just for work we use tabs because "modern"

**Comment by friederbluemle** [comment]
> I'm not sure what you are citing but I can set that up. It's just for work we use tabs because "modern"

I just cited what you wrote in the PR description and tried to help ;) As you can see in the screenshot, the added lines are indented with 2 tab characters, instead of 4 space characters, that's why they appear at a different indentation level.

**Comment by brorbw** [comment]
I mean your quote 
> There is also an issue with the length of the commands and naming that kinda violates the current indentation.
It seems a little out of context?

**Comment by brorbw** [comment]
> > I'm not sure what you are citing but I can set that up. It's just for work we use tabs because "modern"
> 
> I just cited what you wrote in the PR description and tried to help ;) As you can see in the screenshot, the added lines are indented with 2 tab characters, instead of 4 space characters, that's why they appear at a different indentation level.

LOL, k thats not what I meant at all. Im fully aware of the difference between 2 tabs and 4 spaces. My tab width in C-mode in emacs is set to 2 spaces thus my lines are exactly the same indent level as the others. What i meant is that there is an issue with the length of the "commands"  i.e. the ones you call from .yabairc. 
In order to make the commands meaningfull they had to be longer than the previous ones.

**Comment by brorbw** [comment]
You know what. That wasn't even what I meant. 
Screenshot 2020-01-28 at 14 38 36
This was what i meant

**Pull request closed without merging**
