### PR TITLE
Add `window_border_radius` config to Yabai

### PR DESCRIPTION
**Pull request by tsujp**
- Add message
- Add entry in struct
- Change border refresh in `border.c` to prevent unnecessary computation

### CODE REVIEW

**Comment by tsujp** [comment]
I have completely arbitrarily chosen the limits for this API, and was unsure what value to use for "let yabai do it" and so chose `-1` even though it's often used for other things.

The API is:

* Value of `0` is of course no radius and so square.
* Can go up to and including `20`.
* Value of `-1` means yabai will auto size the border radius as it already does.

**Comment by koekeishiya** [comment]
Would you mind creating an *issue* for this, and add it to the list of changes (*repo/CHANGELOG.md*). Otherwise, it seems fine.

**Comment by tsujp** [comment]
Done and done (https://github.com/koekeishiya/yabai/issues/281) @koekeishiya was my protocol here the right one for a PR? Apologies if I should have made an issue first.

**Comment by koekeishiya** [comment]
No need to add *2.0.2* yet, just add it under the *Unreleased* section. I usually don't designate a version number until the release is published. That way it is easier to track all unreleased changes, rather than having to compare the last released version with w/e you are looking at in the changelog.

**Comment by tsujp** [comment]
Whoops, fixed for ya

**Comment by koekeishiya** [comment]
It appears you don't have the latest change I made recently. Could you fix the merge conflict and rebase the PR into a single commit (cleaner history, usually not too concerned with this, but it's nice for PRs).

**Comment by tsujp** [comment]
Fixed conflict, and squashed all commits into first one.

**Comment by koekeishiya** [comment]
Thanks

**Comment by koekeishiya** [comment]
I forgot documentation and sample config was a thing, but I've fixed those now.

**Comment by tsujp** [comment]
Happens to the best of us, I added a simple entry (under title `Window modifications`) in the wiki at the bottom here: https://github.com/koekeishiya/yabai/wiki/Configuration

**Pull request merged**
