### PR TITLE
fix(examples): Working skhd example config for creating new desktops

### PR DESCRIPTION
**Pull request by uri**
Not sure if this is the best approach, but this is what I'm currently using. I guess the format for `yabai -m query --displays --display` has change recently.

### CODE REVIEW

**Comment by dominiklohmann** [comment]
A much more robust solution would be to add a comment above the shortcut instructing to install `jq` (available from Homebrew) and use this code:

Using `grep` and `sed` for this is bound to break again and `jq` is basically `awk` for json, which is the tool to use for this.

```sh
yabai -m space --create && \
    index="$(yabai -m query --displays --display | jq '.spaces[-1]')" && \
    yabai -m window --space "${index}" && \
    yabai -m space --focus "${index}"
```

Note:

```sh
yabai -m query --displays --display | jq '.spaces[-1]'
# above is slightly faster than below, 
# but use the below if you need more than just the index
yabai -m query --spaces --display | jq '.[-1].index'

**Comment by uri** [comment]
I think `jq` is a much better solution for the individual, but for the example config files it would be better to reduce as much friction as possible when getting started with the project.

**Comment by dominiklohmann** [comment]
Using anything but `jq` here is likely to lead to the same issue again at a later point. The format will always be json, but the formatting may change again.

**Comment by uri** [comment]
> The format will always be json, but the formatting may change again.

Yeah that's a solid argument!

**Comment by dominiklohmann** [comment]
@koekeishiya you changed this on master like I posted above, and I just noticed an issue with it (that was present in the versions without jq as well).

Creating a new space inserts it as the last non-fullscreen space in the current display. This means that the correct way to grab the space index is to filter out the native-fullscreen spaces on the current display and then get the last entries index.

```sh
yabai -m space --create && \
    index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
    yabai -m space --focus "${index}"
```

**Pull request closed without merging**
