### PR TITLE
use mach API to inject payload on Big Sur

### PR DESCRIPTION
**Pull request by koekeishiya**
This branch uses the mach API instead of the scripting-bridge framework to inject the payload into Dock.app on macOS Big Sur. Yabai will no longer be able to automatically load the payload upon startup, because the injection has to be performed as the root user. The following steps can be used to test this:

1. Clone this branch and run `make clean && make install`
2. install osax: `sudo yabai --install-sa`
3. Open Console.app and filter messages for `yabai-sa`
4. load osax: `sudo yabai --load-sa`
5. Check the log inside Console.app to see if the injection succeeded. Should look something like this: 
Screenshot 2020-10-03 at 13 55 26

### CODE REVIEW

**Comment by FraserEmbrey** [comment]
I have tried this but all I get is an error when running `yabai --load-sa`
> could not retrieve task port for pid: 1353
> yabai: scripting-addition failed to inject payload into Dock.app!

Yabai was installed using homebrew, then as suggested I cloned this branch and used it to run the install and load commands. Brew services is being used to run yabai.

**Comment by koekeishiya** [comment]
You need to run the load command as root, as mentioned above.

**Comment by FraserEmbrey** [comment]
I know, and I did. I ran both the install and load commands as root

**Comment by koekeishiya** [comment]
Well then I guess support for this software ends with Catalina.

**Comment by folke** [comment]
I don't get the same errors as @FraserEmbrey, but it's not working either.

Running this on the latest public beta (20A5384c), so not the latest developer beta 9.

```shell
$ sudo bin/yabai --install-sa

$ sudo bin/yabai --load-sa
yabai: scripting-addition could not load, make sure SIP is disabled!

$ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
```

**Comment by Liquidmantis** [comment]
Well, the good news is I had better luck than @FraserEmbrey.  I went ahead and uninstall the homebrew build, followed the steps detailed for building the `mach` branch, and copied the compiled yabai binary to /usr/local/bin.  I can run yabai interactively and everything works fine, but I don't get any notification about the sa injection.

I then tried to trick Homebrew by using it to install yabai and swapping the binary for the one I compiled, so that I could use brew services to run it as a daemon.  Then I get a notification loop of `scripting-addition failed to inject payload into Dock.app`.

I instead tried `launchctl -l yabai -p /usr/local/bin/yabai` and that is running yabai as a service, but I don't get the injection notification, nor do I see anything logged in Console.  However yabai appears to be working fine.

**Comment by koekeishiya** [comment]
@folke Looks like it used the old path on your system. I added a commit that recognizes big sur as both 11.0 and 10.16, can you try again?

**Comment by Liquidmantis** [comment]
@folke you have to load with root:
image

**Comment by folke** [comment]
@koekeishiya works!

I still don't see any messages in the console about yabai-sa though, but everything does seems to work.

**Comment by Liquidmantis** [comment]
So far it seems like space management isn't working.  I can change the layout of a space, toggling between stack and bsp modes, but I can't create a space or switch focus.  Similarly, while I can switch to stacking, I can't cycle through the stack anymore.

**Comment by jonathanwilner** [comment]
Tried to install from the mach branch on latest Big Sur, having trouble installing the Scripting Addition. 

Here's the output from Console:

default	08:52:11.608146-0700	appleeventsd	Unable to add send right to port ( port:38479/0x964f rcv:0,send:0,d:2 limit:0) for app App:"yabai"/[ NULL ] /[ NULL ]  1288/0x0:0x0 0x000000000000 sess=100006 so other applications will be unable to send this application AppleEvents.

**Comment by jonathanwilner** [comment]
Works for me from the Mach branch ! Thanks @koekeishiya !

**Comment by koekeishiya** [comment]
> Works for me from the Mach branch ! 

Aight seems promising then, gonna assume some sort of user error or something for the other reports here.
I'm in the process of setting up a Big Sur VM to verify myself.

**Comment by FraserEmbrey** [comment]
I see a lot of these messages in my console:
```
skipped scripting addition "/Library/ScriptingAdditions/yabai.osax" because it is not signed by Apple.
```

**Comment by FraserEmbrey** [comment]
Running yabai as a service via launchctl doesn't seem to work for me. I used `launchctl submit -l yabai -p (which yabai)`—yabai has been installed into `/usr/local/bin/yabai` with the the compiled binary from latest mach branch.

Running in a terminal emulator does work, I can get window balancing and tree rotation to work after starting it. However everything stops working and the commands will hang if I try something like `yabai -m space --create`

**Comment by koekeishiya** [comment]
I got a Big Sur VM up and running, but cannot enter recovery mode to disable SIP. 
Tried multiple ways to this, and it appears to either be a bug with vmware 12 or with the Big Sur Beta 9.
This is just great..

**Comment by ftpd** [comment]
Im trying to get it working, but still no luck with creating/focusing to spaces (elaborated in #678, which I closed when I was asked to continue here or in #589).
--install-sa works from `mach` branch, though.

**Comment by nfrankmai** [comment]
I can confirm that this branch is now working for me on the latest beta however I was unable to get it to launch automatically and run in the background using launchctl so in the meantime I have it running in the background manually using a detached tmux session.

**Comment by ftpd** [comment]
> I can confirm that this branch is now working for me on the latest beta

Can you confirm that `yabai -m space --create` from this branch is working for you too?

**Comment by koekeishiya** [comment]
The changes on this branch do not necessarily make all features work properly, it is primarily meant for testing the change in injection method, as per my instructions in the first post. The patterns and offsets likely require an update as well for beta version 7, 8 and 9.

**Comment by ftpd** [comment]
Ok, so I will wait patiently and observe progress in #589 - injection works now, thanks for that.

**Comment by koekeishiya** [comment]
I'll take it the injection works, so I'll merge this to master. Will update for beta 9 later.

**Comment by FraserEmbrey** [comment]
I haven't checked before so this may be typical behaviour but I ran yabai from my shell and then detected the session as @nfrankmai has as well. After a while I see a lot of yabai processes running. This seems to interfere with passing messages as I get a "failed to connect to socket" message

**Comment by Liquidmantis** [comment]
@koekeishiya Did you already try the CLI commands for getting into recovery mode?  I'm guessing the answer is yes, but just in case:
```
sudo nvram "recovery-boot-mode=unused"
sudo reboot recovery
```
From: https://apple.stackexchange.com/questions/210817/disable-system-integrity-protection-on-os-x-running-on-vmware

**Comment by lbibass** [comment]
I keep getting "sudo: yabai: command not found" when I try to run the --install-sa part. Any ideas?

**Comment by koekeishiya** [comment]
@Liquidmantis yep, I tried like 4 different ways, none of them work.

**Comment by Liquidmantis** [comment]
@lbibass it builds into the ./bin directory, so you need to switch to it or copy the yabai binary to a directory in your path.

**Pull request merged**
