### PR TITLE
Add more options for mouse actions

### PR DESCRIPTION
**Pull request by sourtin**
This pull request makes two main changes:

1. Add `move2` option to mouse actions, which uses a less performant approach but which does not rely on scripting-addition, as detailed [here](https://github.com/koekeishiya/yabai/issues/468).
2. Allow mouse action modifiers to be composed, using `+` as a delimiter, for example `cmd+shift+fn`. Also provides `super` for `cmd+alt+shift+ctrl`.

### CODE REVIEW

**Comment by koekeishiya** [comment]
I'm not interested in adding non-sip support in places where sip offers a better experience. I'll leave this PR open so that it is easier for people to see and they can merge it themselves in a fork/clone if they want to.

I might look into finishing the support for multiple modifiers in *mouse_modifier* in the future.

**Comment by aws-nlaquet** [comment]
Awesome! Looking forward to this release as I was literally just searching for this feature. Just wanted to drop in and say that I really appreciate all of the work you do on this project!

**Comment by sourtin** [comment]
@aws-nlaquet just so you know koekeishiya isn't merging this particular pull request as my approach doesn't quite align with his. Not sure of the timeline for multiple modifier keys in the official branch, but if you want them now you can install my [fork](https://github.com/sourtin/yabai) (which I try to keep up to date with upstream) :)

**Comment by 20015jjw** [comment]
Nice. Since qmk doesn't support mapping to fn, this feature is critical to me... Thanks a lot to both you and @koekeishiya in advance and looking forward to the release!

**Comment by luisdavim** [comment]
> I'm not interested in adding non-sip support in places where sip offers a better experience. I'll leave this PR open so that it is easier for people to see and they can merge it themselves in a fork/clone if they want to.
> 
> I might look into finishing the support for multiple modifiers in _mouse_modifier_ in the future.

Would you at least be interested in reducing the areas where SIP is required? Lots of us use corporate laptops and disabling SIP is not an option...

**Comment by pencilcheck** [comment]
What is the workaround now officially?

**Comment by koekeishiya** [comment]
I'll look into this a bit in the near future, considering the original plans I had (and have mentioned before) are far in the future if ever.

**Comment by koekeishiya** [comment]
I've been thinking about how to approach this, and these are my thoughts so far:

The current system may lack in flexibility in terms of customization, but it is well designed and makes sense in my opinion. The features that are there complement each other well. Let's break down why:

1. The mouse_modifier defines a key which is required to do mouse interactions.
2. This mouse_modifier amplifies the focus-follows-mouse functionality, acting as a way to temporarily disable it while reaching for the menubar or just otherwise skipping activation while the user moves the mouse for whatever reason.
3. When mouse_modifier is combined with left or right mouse-buttons, it triggers the action associated through mouse_action1/2.
4. mouse_drop_action is clearly separate from the "button" actions.

The syntax for achieving the above is simple and clean, in my opinion.
Now I do agree that the functionality supported by this design may be lacking.

I am unable so far to come up with a design that I think is good, that still allows for the interoperability with mouse_modifier and focus-follows-mouse, while still allowing the full flexibility for having multiple modifiers, re-using the same mouse-button with different modifiers, and having the drop_action change based on modifier etc.

I could obviously implement this functionality in code without any problem, but I do care about the design; what the interface looks like, and how each part of the funcitonality complements (or contradicts) other parts.

**Pull request closed without merging**
