### PR TITLE
CPU meter

### PR DESCRIPTION
**Pull request by jkorinth**
Adds a CPU meter graph display to the `yabai` status bar:
cpu-meter

Each line graph shows:
  * user cpu load as white line + fill
  * kernel cpu load as blue line

Configurable options:
  * `status_bar_cpu_meter`: enable/disable feature
  * `status_bar_cpu_user_color`: color for user line
  * `status_bar_cpu_sys_color`: color for kernel line
  * `status_bar_cpu_sample_width`: width per sample (controls overall width of graphs)
  * `status_bar_cpu_update_freq`: cpu load update frequency (default: 1s)

To enable higher update rates, the bar refresh interval is now also configurable via `status_bar_refresh_frequency` (see `doc` updates) and should be set to at least `status_bar_refresh_frequency` for smooth drawing.

### CODE REVIEW

**Comment by lbibass** [comment]
Any updates on this pull request? It seems like a fantastic feature that doesn't add any bloat.

**Comment by brorbw** [comment]
I will refer to [this](https://github.com/koekeishiya/yabai/pull/287#issuecomment-544404750).

**Comment by tanishq-dubey** [comment]
@koekeishiya has stated in the wiki that menubar pull requests relating to features would probably be ignored, just because the focus of this repo is not the menubar. Perhaps we can separate the menubar into a separate repository that can be triggered via yabai signals (similar to how skhd was separated from kwm long ago). Thoughts?

**Comment by brorbw** [comment]
> @koekeishiya has stated in the wiki that menubar pull requests relating to features would probably be ignored, just because the focus of this repo is not the menubar. 

The menu bar is pretty much integrated into yabai atm - it uses some of the same functions to draw as the border around windows etc. I'm not saying that it is impossible but a little cumbersome.

> Perhaps we can separate the menubar into a separate repository that can be triggered via yabai signals (similar to how skhd was separated from kwm long ago). Thoughts?

iirc this is a design decision inherited from bspwm and sxhkd but i could be wrong.

 [https://github.com/koekeishiya/yabai/pull/287#issuecomment-544425222](https://github.com/koekeishiya/yabai/pull/287#issuecomment-544425222)

**Comment by tanishq-dubey** [comment]
It might be a two/three phase move:

 1. Add proper commands/signals to yabai to support a bar
 (1.5. Create a `yabai.h` header with common functions/defines?)
 2. Move the bar to it's own repo

I could even see übersicht widgets benefiting from adding what we might call "bar support" to yabai, although this bar support is moving more along the lines of providing support for external applications to leverage yabai in a more powerful way.

**Comment by brorbw** [comment]
> 1. Add proper commands/signals to yabai to support a bar

I think it should be independent from yabai and have nothing to do with the yabai configuration other that maybe a socket to tell the bar about current desktop (workspace) and current application. I should be socket based and event based. That part is easy. 

> 2. Move the bar to it's own repo

You need to extract the bar from the current project. Pulling the necessary part out of yabai in order to create the same bar with new modifications. 

I like the bar that @koekeishiya has made because it is written in C. 
Übersicht is for me too resource hungry. I would much rather have the bar that is already in this project with my own changes. 
The idea of adding support, i.g. an interface in witch a bar can be implemented is an idea that i support and i even started a couple of months back but i realised that it was easier to just add my changes to the yabai codebase.

**Comment by koekeishiya** [comment]
@tanishq-dubey 

> @koekeishiya has stated in the wiki that menubar pull requests relating to features would probably be ignored, just because the focus of this repo is not the menubar. Perhaps we can separate the menubar into a separate repository that can be triggered via yabai signals (similar to how skhd was separated from kwm long ago). Thoughts?

@brorbw 

> iirc this is a design decision inherited from bspwm and sxhkd but i could be wrong.

While you are correct in that the focus of this repo is not the menubar, I suppose what I didn't get across properly is that ideally yabai would not even have a menubar associated with it - it's not really a part of the package that I want to deliver (in high quality) and be in charge of. 

You are somewhat correct in that the separation of hotkeys into a separate program was definitely inspired by the structure of bspwm. There were multiple reasons for this; firstly, having a CLI for interacting with yabai (the way bspwm does) seemed far superior for integration with external tools, and secondly, there was (in my opinion) a huge lack of lightweight and easy to configure tools for creating global hotkeys on macOS. 

> The menu bar is pretty much integrated into yabai atm - it uses some of the same functions to draw as the border around windows etc. I'm not saying that it is impossible but a little cumbersome.

I wouldn't say that the bar is integrated in a coupled way. These are simply macOS API functions and can be called from any program without special treatment, by linking to the proper frameworks.
In this case I use the private SkyLight framework to access a simple drawing context that will allow me to use Quarts2d drawing environment from C. If you don't mind Obj-C or Swift or whatever, you can do this easily without resorting to undocumented functions.

The bar integrated with yabai at the moment does not do anything that could not be achieved through an external program that simply responds to the existing signal and query system that yabai provides.

What I would propose is making a completely separate application / project that does all of this in a proper way. Looking at the various bar-projects that are available for X11 as an inspiration would be the first step if I were to do this myself. If you have experience within this domain, then simply experiment on your own and slowly build something that can be shipped to the public.

The bar implemented in yabai is literally the dumbest thing possible that I happened to implement because Übersicht stopped working on my macOS after I updated to the latest version, and it was quite frankly simpler to just write the config I had in C, instead of trying to debug the browser Stack of Übersicht. The reason I added it to yabai as well is simply because a lot of people emailed me asking for my config. 

I'd like to have an alternative bar that I could run and remove this code from yabai itself. It is just not the kind of project I prioritize in the foreseeable future.

**Comment by brorbw** [comment]
^ yes

**Comment by qaisjp** [comment]
Wowee, I just want to say that this is very pretty! Nice work.

**Comment by FelixKratz** [comment]
Thanks for the inspiration, I took part of your code and modified it as part of this project: https://github.com/FelixKratz/SketchyBar

**Comment by jkorinth** [comment]
Looks very nice! Will try it ASAP! 👍

Jens

**Pull request closed without merging**
