### PR TITLE
Restructure the repo and README

### PR DESCRIPTION
**Pull request by dominiklohmann**
This ties in with a restructuring effort for the wiki and the new, excellent banner by @fools-mate.

This is still a WIP, just wanted to get some feedback on the layout of the redesigned README. I'll unset the draft mode once I'm done so it can get merged. Take a look at a rendered preview here: https://github.com/dominiklohmann/yabai/blob/restructure/README.md

I am about to merge CODESIGN into the wiki (very soon, w/ lots of other changes and updates for 2.x) and I merged the CHANGELOG into the REAEDME already. Links in the Releases section will have to be changed by a maintainer/collaborator.

~I added the assets to the repo, and while I'd have preferred to use git-lfs to upload the .png assets, GitHub currently does not support uploading git-lfs objects to public forks for non-enterprise accounts.~
Edit: Am collaborator now, thanks @koekeishiya—will upload via git-lfs outside of this PR.

I also have some issue templates planned, but I'm not sure if these can be added via PRs. ~I think they need to be configured by a maintainer/collaborator.~

A 1280x640 (that's already 2x) banner can be used as a social media preview as well, ~but that also needs to be configured by a maintainer/collaborator.~

### CODE REVIEW

**Comment by koekeishiya** [comment]
Looks great so far. I noticed that you removed the thing about placement of the config file - I assume  this will be put in the wiki when the update happens (as it is not there as of now).

I'm also not sure if I like that the changelog is a part of the readme. I think that the changelog and the contents of the readme has a different target audience. Someone looking through the readme to get an idea of what yabai is probably doesn't care much about the latest changes; especially if the list of recent changes is large (e.g  the list of v2.0.0).

**Comment by dominiklohmann** [comment]
> I think that the changelog and the contents of the readme has a different target audience.

That's a point of view I did not consider. I just didn't think the changelog was easily discoverable.

> placement of the config file - I assume this will be put in the wiki when the update happens

That's correct. I was waiting for the 2.0 release as there were so many unreleased changes, and I'm gonna push the changes when I get back home after the weekend. They've been sitting in a private repo for a while now, and just need a short review that I've been delaying lately. The wiki is still at 1.1.2 currently.

Upon further research, a social media banner and issue templates can only be set by repository owners for account-owned (public) repositories, or by maintainers for organization-owned (public) repositories. This is apparently where the account-owned/org-owned border comes in, the collaborator privilege comes with everything except the settings tab. At least now I can upload the files, you'll just have to enable them afterwards.

**Comment by dominiklohmann** [comment]
Closing this in favor of #247 so that the assets can be added using git-lfs. I can't do that from a fork, sadly.

**Comment by koekeishiya** [comment]
> Upon further research, a social media banner 

I assume this is the *Social Preview* thing. Is there an appropriately sized image in the assets folder that I can set it to?

**Comment by dominiklohmann** [comment]
I'll get you one, it needs a very high margin. There's an example file available for download just below where you can set it. It's basically what Twitter/Facebook/Reddit etc. use for previews when the repo is linked, and it defaults to your profile picture if I recall correctly. 

Will be back home in the evening, which is when work on the restructuring continues. Just wanted to push this one out a bit ahead so I can use the vector graphics in the wiki later today, which is necessary because I cannot upload vector graphics to GitHub issues.

**Comment by koekeishiya** [comment]
Aight that's fine. Just ping me whenever you have had the time and I'll see if I can get it up asap :)

**Comment by koekeishiya** [comment]
@dominiklohmann 

Is it fine with you if I take some of what you did in the readme here and repurpose it to replace the current one?

**Comment by dominiklohmann** [comment]
Sure, feel free to do so.

**Pull request closed without merging**
