### PR TITLE
WIP: space swapping functionality

### PR DESCRIPTION
**Pull request by jneen**
A very experimental implementation of #549

### CODE REVIEW

**Comment by koekeishiya** [comment]
Instead of looping though all the windows and calling `space_manager_move_window_to_space` it would be way more efficient to move them all at once:

```
static bool move_all_windows(uint32_t *window_list, int window_count, uint64_t sid)
{
    if (!window_list) return false;
     
    debug("%s: %d -> %lld\n", __FUNCTION__, window_count, sid);
    CFArrayRef window_list_ref = cfarray_of_cfnumbers(window_ist, sizeof(uint32_t), window_list_count, kCFNumberSInt32Type);
    SLSMoveWindowsToManagedSpace(g_connection, window_list_ref, sid);
    CFRelease(window_list_ref);

    return true;
 }
```

Regarding views, they are mapped in the *view table* by their sid (space id). The view struct also contains the sid and suuid as they are returned as attributes through the query system.
Managed windows are mapped to the view struct belonging to the space they are managed at.

A proper swap would look something like the following:

```
    struct view *a_view = table_find(&g_space_manager.view, &a_sid);
    struct view *b_view = table_find(&g_space_manager.view, &b_sid);

    table_remove(&g_space_manager.view, &a_view->sid);
    table_remove(&g_space_manager.view, &b_view->sid);

    uint64_t tmp_sid = a_view->sid;
    CFStringRef tmp_suuid  = a_view->suuid;
    a_view->sid = b_view->sid;
    a_view->suuid = b_view->suuid;
    b_view->sid = tmp_sid;
    b_view->suuid = tmp_suuid;

    table_add(&g_space_manager, &a_view->sid, &a_view);
    table_add(&g_space_manager, &b_view->sid, &b_view);

    // swap labels..

    // refresh space if visible, else flag as invalid to force refresh upon next activation
```

I haven't looked at the actual swapping logic yet for situations where there are multiple spaces remaining.

**Comment by jneen** [comment]
Finally getting around to looking at this, this is all really good info, thanks :]. Am I right in assuming nothing should have to be done with window_manager?

**Comment by koekeishiya** [comment]
Yeah, all window state should be fine as is, as long as the space structures are swapped correctly.

**Comment by jneen** [comment]
I've been using this in the form I just pushed, and it's been very satisfyingly stable. Swapping all the windows and config between spaces seems just generally far less error-prone than moving spaces between displays.

**Comment by UnchartedSystems** [comment]
This seems like a great feature, any update on considering merging this to master?

**Comment by jneen** [comment]
rebased again.

**Comment by senolfeldmann** [comment]
Any update on this feature?

**Comment by koekeishiya** [comment]
Implemented on master:

>--switch <SPACE_SEL>
>>The selected space will always be the currently focused space.
The given space becomes the active space of the focused display regardless of which display it belongs to.
If the selected space and the given space belong to different displays, this behaves like --swap.
If the selected space and the given space belong to the same display, this behaves like --focus.
System Integrity Protection must be partially disabled.

There is no `window --switch ..` command, however it would just need to chain the following:

```
yabai -m window --space 5 && yabai -m space --switch 5`
```

**Pull request closed without merging**
