### PR TITLE
Reorder resize vs move based on size delta

### LINKED ISSUE #1388: New window sometimes exceeds layout node boundaries
When creating a new window, the size of the window sometimes exceeds the layout node's boundaries, especially when there are many windows on screen and the new window is deep in the node tree. See attached video for example. See linked PR for debugging information and a proposed fix.

### PR DESCRIPTION
**Pull request by overhacked**
When setting the size of a window via `window_manager_set_window_frame`,
either resize before moving, if the window is getting smaller, or
move before resizing, if the window is getting bigger. This avoids
window size conflicts with the system window manager boundaries, like
display edge. If a too-big window is moved to the edge of the screen,
the system display manager will force it to be resized to fit within
the screen dimensions, and the `AXUIElementSetAttributeValue` API call
issued by yabai to resize it gets ignored.

Potentially fixes #1388.

### CODE REVIEW

**Comment by koekeishiya** [comment]
Waiting to merge until it is confirmed as a proper fix.

**Comment by overhacked** [comment]
> Waiting to merge until it is confirmed as a proper fix.

It’s been working for me so far; I’d love anyone else reading this to check it out.

**Comment by koekeishiya** [comment]
> This is the way to go anyways imo, as it reduces the visual flicker on window movement + resize. Before, windows would flicker over the other windows in the grid (being moved at larger size) and only afterwards be resized down to fit the grid again.

There used to be a resize there until I apparently accidentally committed the following local change:
 
https://github.com/koekeishiya/yabai/commit/1e00a59205409587fd8194d50f004e87118da9a3

**Comment by koekeishiya** [comment]
I've added back the line that I accidentally removed earlier, but I don't think this is mergeable, because the frame cache guard is not working properly, so relying on that to also perform this shrinking vs not shrinking check is also not reliable.

**Pull request closed without merging**
