### PR TITLE
Fix yabai SIP-disabled features for MacOS 13.3

### PR DESCRIPTION
**Pull request by gur111**
This isn't perfect, some functions can't be hooked properly on some machines.
Some functions I don't don't always work: `get_remove_space_pattern`, `get_set_front_window_pattern`, `get_dppm_pattern`.
The patterns need some working.

That being said, I spent an entire day finding the patterns for the functions that do work and on my machine it works.
As I'm very rusty with `radare2` I have no intention of pursuing this PR. If anyone wants to take over, be my guest. 

disclaimer: I also didn't check that this is backward compatible with older versions.

### CODE REVIEW

**Comment by gur111** [comment]
@koekeishiya can you take a look and see if you want it in the mainline? If not, people who this amazing piece of software unusable after updating, feel free to follow the usual dev installation instructions except do:
```
brew install gur111/formulae/yabai --HEAD
```
instead of the main repo.

**Comment by koekeishiya** [comment]
I usually don't focus on beta versions. From prior experience the offsets change heavily between different beta builds and are not equal to the final release version. I'll usually spend half an hour to fix it after the release is live.

**Comment by koekeishiya** [comment]
@gur111 I replied to your message on patreon. I don't really log in there that often, so apologies for the late reply.

**Comment by zchlm** [comment]
@koekeishiya Would be great to have this merged now that MacOS 13.3 is released.

**Comment by koekeishiya** [comment]
Upgrade to v5.0.3 for macOS 13.3 support.

**Pull request closed without merging**
